### ISSUE TITLE
shibui-dropdown-menu is featured in one of our blogs

### ISSUE THREAD

**Issue by binhbbbb** [ShibuiElements/shibui-dropdown-menu#20]
Hey ShibuiElements,

Your component, shibui-dropdown-menu, was recently featured in one of our blogs, [Top 6 drop-down UI web components](https://vaadin.com/blog/wcw-24-dropdown-components). It's a great component and I'm sure people would love it. It would be great if you have time to read the blog.

Regards,
Binh

**Comment by nick-woodward** [comment]
Thanks for the heads up, I'll check it out when I get the chance!
