### ISSUE TITLE
Unable to use 'alignment' property for 'shibui-dropdown-menu'

### ISSUE THREAD

**Issue by tekreme73** [ShibuiElements/shibui-dropdown-menu#22]
### Description
When using `shibui-dropdown-menu`, I can't use the `alignment` property.

### Expected outcome

When the `alignment` property is set to `right`, the dropdown have to be align to the right of the trigger.

### Actual outcome

The `alignment` is not considered and is by default align to the left of the trigger.

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 11
- [x] Safari 10
- [x] Safari 9
- [x] Edge
- [x] IE 11

**Comment by nick-woodward** [comment]
This issue should now be resolved in [v1.2.1](https://github.com/ShibuiElements/shibui-dropdown-menu/releases/tag/1.2.1).
