### ISSUE TITLE
Add support for automatic alignment

### ISSUE THREAD

**Issue by hatpick** [ShibuiElements/shibui-dropdown-menu#4]
### Description

If the trigger is close to the page limit (top right), menu is drawn out of the page.

### Live Demo

https://jsbin.com/hoyinasaba/1/edit?html,output

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [x] IE 11
- [ ] IE 10

**Comment by nick-woodward** [comment]
Hey @hatpick is the instance you're running into similar to this?

### Live Demo

https://jsbin.com/hoyinasaba/1/edit?html,output

**Comment by hatpick** [comment]
@nick-woodward yes
